<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <PackageId>com.noahjutz.hellogrpcunitycontract</PackageId>
        <Version>1.0.0-dev02</Version>
        <Authors>Noah Jutz</Authors>
    </PropertyGroup>

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <LangVersion>latestMajor</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    
    <ItemGroup>
        <Protobuf Include="../proto/*.proto" GrpcServices="Server" />
    </ItemGroup>
    
    <ItemGroup>
      <PackageReference Include="Google.Protobuf" Version="3.36.2" />
      <PackageReference Include="Grpc.Core" Version="2.46.6" />
      <PackageReference Include="Grpc.Tools" Version="2.84.0">
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        <PrivateAssets>all</PrivateAssets>
      </PackageReference>
    </ItemGroup>

</Project>
